export const AUTH_ERROR_CODES = {
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
} as const;

export const AUTH_DEFAULTS = {
  INITIAL_ELO: 1000,
  INITIAL_DEEN_POINTS: 50,
  MIN_PASSWORD_LENGTH: 8,
  ACCESS_TOKEN_EXPIRY_SECONDS: 3600,      // 1 hour
  REFRESH_TOKEN_EXPIRY_SECONDS: 604800,   // 7 days
} as const;

export const RATE_LIMITS = {
  SIGNUP: { windowMs: 60_000, maxRequests: 5 },
  LOGIN: { windowMs: 60_000, maxRequests: 10 },
  PASSWORD_RESET: { windowMs: 60_000, maxRequests: 3 },
} as const;