// shared/src/types/errors.ts

export const MATCH_ERROR_CODES = {
  // Matchmaking errors
  ALREADY_IN_QUEUE: 'ALREADY_IN_QUEUE',
  NOT_IN_QUEUE: 'NOT_IN_QUEUE',
  QUEUE_FULL: 'QUEUE_FULL',
  MATCHMAKING_TIMEOUT: 'MATCHMAKING_TIMEOUT',

  // Match errors
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  MATCH_ALREADY_STARTED: 'MATCH_ALREADY_STARTED',
  MATCH_NOT_IN_PROGRESS: 'MATCH_NOT_IN_PROGRESS',
  MATCH_ALREADY_ENDED: 'MATCH_ALREADY_ENDED',
  NOT_MATCH_PARTICIPANT: 'NOT_MATCH_PARTICIPANT',

  // Question / answer errors
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  ANSWER_ALREADY_SUBMITTED: 'ANSWER_ALREADY_SUBMITTED',
  ANSWER_OUT_OF_ORDER: 'ANSWER_OUT_OF_ORDER',
  INVALID_ANSWER_INDEX: 'INVALID_ANSWER_INDEX',
  QUESTION_TIMED_OUT: 'QUESTION_TIMED_OUT',

  // Session errors
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Auth / socket errors
  SOCKET_UNAUTHORIZED: 'SOCKET_UNAUTHORIZED',
  SOCKET_INVALID_TOKEN: 'SOCKET_INVALID_TOKEN',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type MatchErrorCode = (typeof MATCH_ERROR_CODES)[keyof typeof MATCH_ERROR_CODES];

export interface MatchError {
  code: MatchErrorCode;
  message: string;
}
